### ISSUE TITLE
The shipped Nerd tree is incompatible with the latest Nerdtree

### ISSUE THREAD

**Issue by xuhdev** [wesleyche/Trinity#2]
The Nerdtree and [the latest version](https://github.com/scrooloose/nerdtree) are both installed, conflicts happen. I'm wondering why you put a Nerd tree there.

**Comment by nschley** [comment]
More specifically to xhudev's comment:
I recall reading that the Trinity version of `NERD_tree.vim` has some specific adaptations from scrooloose's `NERD_tree.vim` of the same vintage (20 July, 2008.)  I just diffed them and found there were not many, and most were 1-line adds or commented-outs.  The biggest was the addition of a new function, `GetEditWin()`, but I don't see anything that wouldn't have been "mergable."
The issue at hand is that Scrooloose's current `NERD_tree.vim` (Jul 14, 2014) is _radically_ different from the 20 July 2008 version:  205 lines versus 3557 lines.
--> Someone will have to put some thought into dealing with change of this extent.

**Comment by wenlongche** [comment]
WAD
